# Generated by Django 5.1.2 on 2024-10-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colegio',
            old_name='direccion',
            new_name='comuna',
        ),
        migrations.RemoveField(
            model_name='colegio',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='colegio',
            name='latitud',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colegio',
            name='longitud',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colegio',
            name='provincia',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
