# Generated by Django 5.1.2 on 2024-10-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_direccion_colegio_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='direccion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
