# Generated by Django 5.1.2 on 2024-10-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_colegio_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colegio',
            old_name='comuna',
            new_name='nombre_comuna',
        ),
        migrations.RenameField(
            model_name='colegio',
            old_name='direccion',
            new_name='nombre_deprov',
        ),
        migrations.RenameField(
            model_name='colegio',
            old_name='nombre',
            new_name='nombre_rbd',
        ),
        migrations.RenameField(
            model_name='colegio',
            old_name='provincia',
            new_name='nombre_region',
        ),
    ]
