# Generated by Django 5.1.2 on 2024-10-22 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_comuna_colegio_nombre_comuna_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='hora_salida',
            new_name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='destino_lat',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='destino_lon',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='origen_lat',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='origen_lon',
        ),
        migrations.AddField(
            model_name='ruta',
            name='capacidad_maxima',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ruta',
            name='destino',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=10),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='frecuencia',
            field=models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='diaria', max_length=50),
        ),
        migrations.AddField(
            model_name='ruta',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='puntos_intermedios',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehiculo'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='alumnos',
            field=models.ManyToManyField(related_name='rutas', to='app.alumno'),
        ),
    ]
