# Generated by Django 5.1.2 on 2024-10-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_hora_salida_ruta_hora_inicio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruta',
        ),
    ]
