# Generated by Django 5.1.2 on 2024-10-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=255)),
                ('puntos_intermedios', models.JSONField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=10)),
                ('capacidad_maxima', models.IntegerField(default=10)),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='diaria', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumnos', models.ManyToManyField(related_name='rutas', to='app.alumno')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.conductor')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehiculo')),
            ],
        ),
    ]
