# Generated by Django 5.1.2 on 2024-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='rutas',
            field=models.ManyToManyField(blank=True, related_name='alumnos_rutas', to='app.ruta'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='alumnos',
            field=models.ManyToManyField(related_name='rutas_alumnos', to='app.alumno'),
        ),
    ]
