# Generated by Django 5.1.2 on 2024-10-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alumno_rutas_alter_ruta_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
