# Generated by Django 5.1.2 on 2024-10-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alumno_conductor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudvinculacion',
            old_name='alumnos',
            new_name='alumno',
        ),
    ]
