# Generated by Django 5.1.2 on 2024-11-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alumno_latitud_alumno_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='paradas',
            field=models.JSONField(default=list),
        ),
    ]
