# Generated by Django 5.1.2 on 2024-11-09 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_viaje_options_remove_viaje_en_viaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ruta'),
            preserve_default=False,
        ),
    ]
