# Generated by Django 5.1.2 on 2024-11-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_viaje_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='apoderados',
            field=models.ManyToManyField(to='app.apoderado'),
        ),
    ]
