# Generated by Django 5.1.2 on 2024-11-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_ubicacion_viaje_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='alumnos',
            field=models.ManyToManyField(related_name='viajes', to='app.alumno'),
        ),
    ]
