# Generated by Django 5.1.2 on 2024-11-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_viaje_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='apoderado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.apoderado'),
        ),
    ]
